parameters:
- name: SolutionName
  displayName: Solution Name
  type: string
  default: 'SampleSolution'
- name: EnvName
  displayName: Source Environment
  type: string
  default: 'Power-platform-Dev-Connection'

trigger: none

# Title case variables denote mapping to a parameter
variables:
  SolutionName: ${{ parameters.SolutionName }}
  SourceEnvSvcConn: ${{ parameters.EnvName }}
  exportBranchName: 'export-$(SolutionName)-$(Build.BuildId)'

jobs:
- job: exportSolution
  displayName: Export Solution

  pool:
    vmImage: windows-2019

  steps:
  - checkout: self
    persistCredentials: True

  # - pwsh: |
  #     $solutionName = "$(SolutionName)"
  #     $exportBranchName = "$(exportBranchName)"
  #     cd $(Build.SourcesDirectory)
  #     git config user.email "dbhuyan@microsoft.com"
  #     git config user.name "Damayanti Bhuyan"
  #     git checkout $(Build.SourceBranchName)
  #     git checkout -b $exportBranchName
  #     git -c http.extraheader="AUTHORIZATION: bearer $env:MY_ACCESS_TOKEN" push --set-upstream origin $exportBranchName
  #   env:
  #     MY_ACCESS_TOKEN: $(System.AccessToken)
      
  - task: PowerPlatformToolInstaller@0
    displayName: 'Power Platform Tool Installer'

  - task: PowerPlatformExportSolution@0
    displayName: 'Power Platform Export Solution'
    inputs:
      authenticationType: PowerPlatformSPN
      PowerPlatformSPN: $(SourceEnvSvcConn)
      SolutionName: $(SolutionName)
      SolutionOutputFile: $(Build.BinariesDirectory)/$(SolutionName).zip

  - task: PowerPlatformUnpackSolution@0
    displayName: 'Power Platform Unpack Solution'
    inputs:
      SolutionInputFile: $(Build.BinariesDirectory)/$(SolutionName).zip
      SolutionTargetFolder: $(Build.SourcesDirectory)/$(SolutionName)
  - powershell: |
      $url = "$($env:SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$env:SYSTEM_TEAMPROJECTID/_apis/build/definitions/$($env:SYSTEM_DEFINITIONID)?api-version=4.1-preview"
      Write-Host "URL: $url"
      $pipeline = Invoke-RestMethod -Uri $url -Headers @{
        Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"
      }
      Write-Host "Pipeline = $($pipeline | ConvertTo-Json -Depth 100)"
    env:
      SYSTEM_ACCESSTOKEN: $(system.accesstoken)    

  - pwsh: |
      cd $(Build.SourcesDirectory)
      git add --all
      git commit -m "$(SolutionName)-$(Build.BuildId)"
      # git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" push
    env:
      MY_ACCESS_TOKEN: $(System.AccessToken)
  # https://marketplace.visualstudio.com/items?itemName=sander-aernouts.git-buildtasks  
#   - task: GitCreatePullRequest@0
#     displayName: Create PR for $(exportBranchName) branch
#     inputs:
#       repositorySelectionMethod: 'currentBuild'
#       sourceBranch: refs/heads/$(exportBranchName)
#       targetBranch: $(Build.SourceBranch)
#       autoComplete: false
#       deleteSourceBranch: true
